#!/bin/bash

BASE16_SHELL=$HOME/.config/base16-shell/
[ -s $BASE16_SHELL/profile_helper.sh ] && \
              eval "$($BASE16_SHELL/profile_helper.sh)"

_base16 "/home/philipp/.config/base16-shell/scripts/base16-gruvbox-dark-hard.sh" gruvbox-dark-hard
