#!/bin/bash
# This script is executed every time a theme is applied.
# Each generator can have it's own _mondo-apply script.

# The default syntax is bash, but by changing the shebang,
# one could use another language (f.i. perl or python).

# $1 is equal to: $MONOD_DIR/generator/TYPE/THEME[.extensions]

# If this script is not needed, this file can safely be removed.
# (removing the file, will improve execution speed)

# MONDO_DIR="${1%%/generator*}"
# THIS_DIR="${1%/*}"
# THIS_GENERATOR="${THIS_DIR##*/}"
# THIS_FILE="${1##*/}"
# THIS_THEME="${THIS_FILE%.*}"

# To source the settings file one could use this:
# source "${THIS_DIR}/_mondo-settings"

theme="/mnt/c/Users/PhilippScheibe/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"

cat $theme | jq ' (.schemes | .[] | select(.name=="Templer").background) |= "#1C2023"
				| (.schemes | .[] | select(.name=="Templer").black) |= "#393F45"
				| (.schemes | .[] | select(.name=="Templer").blue) |= "#AE95C7"
				| (.schemes | .[] | select(.name=="Templer").brightBlack) |= "#747C84"
				| (.schemes | .[] | select(.name=="Templer").brightBlue) |= "#AE95C7"
				| (.schemes | .[] | select(.name=="Templer").brightCyan) |= "#95AEC7"
				| (.schemes | .[] | select(.name=="Templer").brightGreen) |= "#95C7AE"
				| (.schemes | .[] | select(.name=="Templer").brightPurple) |= "#C795AE"
				| (.schemes | .[] | select(.name=="Templer").brightRed) |= "#C7AE95"
				| (.schemes | .[] | select(.name=="Templer").brightWhite) |= "#F3F4F5"
				| (.schemes | .[] | select(.name=="Templer").brightYellow) |= "#AEC795"
				| (.schemes | .[] | select(.name=="Templer").cursorColor) |= "#F3F4F5"
				| (.schemes | .[] | select(.name=="Templer").cyan) |= "#758EA7"
				| (.schemes | .[] | select(.name=="Templer").foreground) |= "#C7CCD1"
				| (.schemes | .[] | select(.name=="Templer").green) |= "#75A78E"
				| (.schemes | .[] | select(.name=="Templer").purple) |= "#A7758E"
				| (.schemes | .[] | select(.name=="Templer").red) |= "#A78E75"
				| (.schemes | .[] | select(.name=="Templer").selectionBackground) |= "#565E65"
				| (.schemes | .[] | select(.name=="Templer").white) |= "#C7CCD1"
				| (.schemes | .[] | select(.name=="Templer").yellow) |= "#8EA775"' > /tmp/settings.json

mv /tmp/settings.json "$theme"
