#!/bin/bash

# This script is executed AFTER all other applying
# actions and scripts are finished, when mondo is 
# executed with the apply option (-a).

# The intension of this script is to let you adjust
# your environment after applying a new theme.

# For instance one might want to reload certain processes
# like windowmanagers and statusbars. 

# $1 in this script contains the output from
# `pre-apply`. By using eval you can pass multiple
# variables and stuff between the scripts.

# eval "${1}"

select=$(mondo get theme)

##### wallpaper or color-theme
####################################################

if [ 'templer' = "$select" ]; then
	## set alpha
	sed -i "s/^\*alpha:.*/\*alpha: 0\.85/g" ~/.config/X11/Xresources
else
	## set alpha
	sed -i "s/^\*alpha:.*/\*alpha: 1\.0/g" ~/.config/X11/Xresources
fi


##### reload terminal
####################################################

  ## source Xresources here not in gnerator for alpha getting loadet
xrdb -merge -I~/.config/X11 ~/.config/X11/Xresources

  ## reaload st-clients
pkill -USR2 "^st$" &

  ## source theme to tmux
tmux source-file -q ~/.tmux.conf


##### set gtk- and icon- theme
####################################################

  ## more colors.....
base02=$(mondo get base02)
base03=$(mondo get base03)
base04=$(mondo get base04)
base05=$(mondo get base05)
base0B=$(mondo get base0B)
base0Ba=$(mondo get base0Ba)
base0D=$(mondo get base0D)
base0Da=$(mondo get base0Da)
base0Dmix=$(pastel mix "$base0D" "$base0Da" | pastel format hex)
base0Ddarker=$(pastel mix "$base0Dmix" "$base02" | pastel format hex)
base0Ddarkera=$(colort -15 $base0Ddarker)
base0Ddarkeraa=$(colort -30 $base0Ddarker)
base0Ddarkeraaa=$(colort -55 $base0Ddarker)
echo "@define-color base0Ddarker $base0Ddarker;" >> ~/.config/X11/xfiles/themes/colordef.css
echo "@define-color base0Ddarkera $base0Ddarkera;" >> ~/.config/X11/xfiles/themes/colordef.css
echo "@define-color base0Ddarkeraa $base0Ddarkeraa;" >> ~/.config/X11/xfiles/themes/colordef.css
echo "@define-color base0Ddarkeraaa $base0Ddarkeraaa;" >> ~/.config/X11/xfiles/themes/colordef.css
sed -i "$ i base0Ddarker:$base0Ddarker" ~/.config/X11/xfiles/themes/colordef.rc
sed -i "$ i base0Ddarkera:$base0Ddarkera" ~/.config/X11/xfiles/themes/colordef.rc
sed -i "$ i base0Ddarkeraa:$base0Ddarkeraa" ~/.config/X11/xfiles/themes/colordef.rc
sed -i "$ i base0Ddarkeraaa:$base0Ddarkeraaa" ~/.config/X11/xfiles/themes/colordef.rc
base0Bmix=$(pastel mix "$base0B" "$base0Ba" | pastel format hex)
base0Bgrey=$(pastel mix "$base0Bmix" "$base05" | pastel format hex)
base0Bgreya=$(pastel mix "$base0Bmix" "$base04" | pastel format hex)
base0Bgreyaa=$(pastel mix "$base0Bmix" "$base03" | pastel format hex)
base0Bgreyaaa=$(pastel mix "$base0Bmix" "$base02" | pastel format hex)
echo "@define-color base0Bgrey $base0Bgrey;" >> ~/.config/X11/xfiles/themes/colordef.css
echo "@define-color base0Bgreya $base0Bgreya;" >> ~/.config/X11/xfiles/themes/colordef.css
echo "@define-color base0Bgreyaa $base0Bgreyaa;" >> ~/.config/X11/xfiles/themes/colordef.css
echo "@define-color base0Bgreyaaa $base0Bgreyaaa;" >> ~/.config/X11/xfiles/themes/colordef.css
sed -i "$ i base0Bgrey:$base0Bgrey" ~/.config/X11/xfiles/themes/colordef.rc
sed -i "$ i base0Bgreya:$base0Bgreya" ~/.config/X11/xfiles/themes/colordef.rc
sed -i "$ i base0Bgreyaa:$base0Bgreyaa" ~/.config/X11/xfiles/themes/colordef.rc
sed -i "$ i base0Bgreyaaa:$base0Bgreyaaa" ~/.config/X11/xfiles/themes/colordef.rc

  ## copy template-icons and set new color
ICON=$(xrdb -query|awk '/\*color19:/ {print $2}')
ICONBAR=$(xrdb -query|awk '/\*color3:/ {print $2}')
cp -rf ~/.config/X11/xfiles/icons/Templer.template/* ~/.local/share/icons/Templer
find ~/.local/share/icons/Templer/status/scalable/ -type f -exec sed -i "s/MAINCOLOR/$ICONBAR/g" {} +
find ~/.local/share/icons/Templer/ -type f -exec sed -i "s/MAINCOLOR/$ICON/g" {} +

  ## apply gtk-theme on the fly
xsettingsd -c ~/.config/X11/xsettingsd &
pkill -SIGHUP xsettingsd && killall xsettingsd

  ## set xmenu icons
convert -size 16x16 -background none ~/.local/share/icons/Templer/apps/scalable/web-browser-symbolic.svg ~/.config/X11/xfiles/icons/web-browser-symbolic.png
convert -size 16x16 -background none ~/.local/share/icons/Templer/actions/scalable/sidebar-places-symbolic.svg ~/.config/X11/xfiles/icons/sidebar-places-symbolic.png


##### restart/source applications
####################################################

  ## nm-applet
killall nm-applet; nm-applet &

  ## polkit-gtk
killall polkit-gnome-authentication-agent-1; /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

  ## dwmblocks
killall -9 dwmblocks
make -C ~/.local/git/dwmblocks
dwmblocks &

  ## qutebroser (in some way it depends on gtk2-stuff and so on colors defined above... i dont know why...)
pgrep qutebrowser && qutebrowser :config-source

  ## source dwm...
xsetroot -name "dwm:cmd xrdb"
