#!/bin/bash

# This script is executed AFTER all other applying
# actions and scripts are finished, when mondo is 
# executed with the apply option (-a).

# The intension of this script is to let you adjust
# your environment after applying a new theme.

# For instance one might want to reload certain processes
# like windowmanagers and statusbars. 

# $1 in this script contains the output from
# `pre-apply`. By using eval you can pass multiple
# variables and stuff between the scripts.

# eval "${1}"

select=$(mondo get theme)

##############################################################################################
##### wallpaper or color-theme ####################################################################################################
##############################################################################################

convert /home/philipp/.xfiles/background/bitmap-walls/patterns/dots_wide.xbm -fill "$(xrdb -query|awk '/\*color20:/ {print $2}')" -opaque "#000000" -fill "$(xrdb -query|awk '/\*color0:/ {print $2}')" +opaque "#ffffff" /home/philipp/.xfiles/background/png-walls/dots8.png
#convert /home/philipp/.xfiles/background/bitmap-walls/patterns/dots_wide.xbm -fill "$(xrdb -query|awk '/\*color20:/ {print $2}')" -opaque "#000000" -fill "$(xrdb -query|awk '/\*color18:/ {print $2}')" +opaque "#ffffff" /home/philipp/.xfiles/background/png-walls/dots8.png
convert /home/philipp/.xfiles/background/png-walls/dots8.png -fill "$(xrdb -query|awk '/\*color20:/ {print $2}')" -opaque "#ffffff" /home/philipp/.xfiles/background/png-walls/dots16.png

if [ 'impler' = "$select" ]; then

  # set alpha
	sed -i "s/^\*alpha:.*/\*alpha: 0\.7/g" ~/.config/X11/Xresources
  # set wallpaper
	hsetroot -fill $(cat ~/.xfiles/impler/wallpaper)
	sed -i "s/^hsetroot.*/hsetroot -fill \$\(cat ~\/\.xfiles\/impler\/wallpaper\)/g" ~/.local/bin/dwm-starter
else

  # set alpha
	sed -i "s/^\*alpha:.*/\*alpha: 1\.0/g" ~/.config/X11/Xresources
  # set wallpaper
	hsetroot -tile /home/philipp/.xfiles/background/png-walls/dots16.png
	#xsetroot -bitmap /home/philipp/.xfiles/background/bitmap-walls/patterns/dots_wide.xbm -fg "$(xrdb -query|awk '/\*color18:/ {print $2}')" -bg "$(xrdb -query|awk '/\*color20:/ {print $2}')"
	#xsetroot -solid "$(xrdb -query|awk '/\*color0:/ {print $2}')"
	#xsetroot -bitmap /home/philipp/.xfiles/background/bitmap-walls/patterns/line_diag8_1.xbm -bg "$(xrdb -query|awk '/\*color18:/ {print $2}')" -fg "$(xrdb -query|awk '/\*color8:/ {print $2}')"

	# make it permanent
	sed -i "s/^hsetroot -fill.*/hsetroot -tile \/home\/philipp\/\.xfiles\/background\/png-walls\/dots16\.png/g" ~/.local/bin/dwm-starter
fi

##############################################################################################
##### reload terminal ####################################################################################################
##############################################################################################
  ## source Xresources here not in gnerator for alpha getting loadet
xrdb -merge -I~/.config/X11 ~/.config/X11/Xresources
  ## reaload st-clients
pkill -USR2 "^st$" &
  ## source theme to tmux
tmux source-file -q ~/.tmux.conf


##############################################################################################
##### restart applications ###############################################################################################
##############################################################################################
  ## nm-applet
killall nm-applet; nm-applet &
  ## polkit-gtk
killall polkit-gnome-authentication-agent-1; /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
  ## dwmblocks
killall -9 dwmblocks
make -C ~/.local/git/dwmblocks
dwmblocks &

##############################################################################################
##### set gtk- and icon- theme ###############################################################################################
##############################################################################################
  ## more colors.....
base02=$(mondo get base02)
base03=$(mondo get base03)
base04=$(mondo get base04)
base05=$(mondo get base05)
base0B=$(mondo get base0B)
base0Ba=$(mondo get base0Ba)
base0D=$(mondo get base0D)
base0Da=$(mondo get base0Da)
base0Dmix=$(pastel mix "$base0D" "$base0Da" | pastel format hex)
base0Ddarker=$(pastel mix "$base0Dmix" "$base02" | pastel format hex)
base0Ddarkera=$(colort -15 $base0Ddarker)
base0Ddarkeraa=$(colort -30 $base0Ddarker)
base0Ddarkeraaa=$(colort -55 $base0Ddarker)
echo "@define-color base0Ddarker $base0Ddarker;" >> ~/.xfiles/themes/colordef.css
echo "@define-color base0Ddarkera $base0Ddarkera;" >> ~/.xfiles/themes/colordef.css
echo "@define-color base0Ddarkeraa $base0Ddarkeraa;" >> ~/.xfiles/themes/colordef.css
echo "@define-color base0Ddarkeraaa $base0Ddarkeraaa;" >> ~/.xfiles/themes/colordef.css
echo "base0Ddarker:$base0Ddarker" >> ~/.xfiles/themes/colordef.rc
echo "base0Ddarkera:$base0Ddarkera" >> ~/.xfiles/themes/colordef.rc
echo "base0Ddarkeraa:$base0Ddarkeraa" >> ~/.xfiles/themes/colordef.rc
echo "base0Ddarkeraaa:$base0Ddarkeraaa" >> ~/.xfiles/themes/colordef.rc
base0Bmix=$(pastel mix "$base0B" "$base0Ba" | pastel format hex)
base0Bgrey=$(pastel mix "$base0Bmix" "$base05" | pastel format hex)
base0Bgreya=$(pastel mix "$base0Bmix" "$base04" | pastel format hex)
base0Bgreyaa=$(pastel mix "$base0Bmix" "$base03" | pastel format hex)
base0Bgreyaaa=$(pastel mix "$base0Bmix" "$base02" | pastel format hex)
echo "@define-color base0Bgrey $base0Bgrey;" >> ~/.xfiles/themes/colordef.css
echo "@define-color base0Bgreya $base0Bgreya;" >> ~/.xfiles/themes/colordef.css
echo "@define-color base0Bgreyaa $base0Bgreyaa;" >> ~/.xfiles/themes/colordef.css
echo "@define-color base0Bgreyaaa $base0Bgreyaaa;" >> ~/.xfiles/themes/colordef.css
echo "base0Bgrey:$base0Bgrey" >> ~/.xfiles/themes/colordef.rc
echo "base0Bgreya:$base0Bgreya" >> ~/.xfiles/themes/colordef.rc
echo "base0Bgreyaa:$base0Bgreyaa" >> ~/.xfiles/themes/colordef.rc
echo "base0Bgreyaaa:$base0Bgreyaaa" >> ~/.xfiles/themes/colordef.rc
  ## copy template-icons and set new color
ICON=$(xrdb -query|awk '/\*color19:/ {print $2}')
ICONBAR=$(xrdb -query|awk '/\*color3:/ {print $2}')
cp -rf ~/.xfiles/icons/Templer.template/* ~/.local/share/icons/Templer
find ~/.local/share/icons/Templer/status/scalable/ -type f -exec sed -i "s/MAINCOLOR/$ICONBAR/g" {} +
find ~/.local/share/icons/Templer/ -type f -exec sed -i "s/MAINCOLOR/$ICON/g" {} +
  ## apply gtk-theme on the fly
timeout 0.1s xsettingsd -c ~/.xfiles/.xsettingsdummy
timeout 0.1s xsettingsd -c ~/.xfiles/.xsettingsd
  ## set xmenu icons
convert -size 16x16 -background none ~/.local/share/icons/Templer/apps/scalable/web-browser-symbolic.svg ~/.xfiles/icons/web-browser-symbolic.png
convert -size 16x16 -background none ~/.local/share/icons/Templer/actions/scalable/sidebar-places-symbolic.svg ~/.xfiles/icons/sidebar-places-symbolic.png


##############################################################################################
###### dwm-xrdb hack.... not refreshing in mondo... + rescale windows to fix glitches ######################################
##############################################################################################
xsetroot -name "fsignal:1"
xsetroot -name "fsignal:2"
