#!/bin/bash

# This script is executed AFTER all other applying
# actions and scripts are finished, when mondo is 
# executed with the apply option (-a).

# The intension of this script is to let you adjust
# your environment after applying a new theme.

# For instance one might want to reload certain processes
# like windowmanagers and statusbars. 

# $1 in this script contains the output from
# `pre-apply`. By using eval you can pass multiple
# variables and stuff between the scripts.

# eval "${1}"


##### reload st-windows
externalpipe_buffer.sh st_reloadsignal


##### tmux-zsh-base16-source

# BASH
#for i in {1..10}; do tmux list-panes -as -F "#{session_name}:#{window_index}.#{pane_index}" | xargs -I PANE tmux send-keys -t PANE 'C-['; done
##tmux list-panes -as -F "#{session_name}:#{window_index}.#{pane_index}" | xargs -I PANE tmux send-keys -t PANE 'C-['
#
#tmux list-panes -as -F "#{session_name}:#{window_index}.#{pane_index}" | xargs -I PANE tmux send-keys -t PANE C-z
#tmux list-panes -as -F "#{session_name}:#{window_index}.#{pane_index}" | xargs -I PANE tmux send-keys -t PANE C-c
##tmux list-panes -as -F "#{session_name}:#{window_index}.#{pane_index}" | xargs -I PANE tmux send-keys -t PANE " source ~/.bashrc; fg &> /dev/null; echo -n" C-m
#tmux list-panes -as -F "#{session_name}:#{window_index}.#{pane_index}" | xargs -I PANE tmux send-keys -t PANE "source ~/.zshrc" C-m
#tmux list-panes -as -F "#{session_name}:#{window_index}.#{pane_index}" | xargs -I PANE tmux send-keys -t PANE "fg > /dev/null 2>&1" C-m

# ZSH
#for i in {1..10}; do tmux list-panes -s -F "#{window_index}.#{pane_index}" | xargs -I PANE tmux send-keys -t PANE 'C-['; done
#tmux list-panes -s -F "#{window_index}.#{pane_index}" | xargs -I PANE tmux send-keys -t PANE C-z # or "#{session_name}:#{window_index}.#{pane_index}"
#tmux list-panes -s -F "#{window_index}.#{pane_index}" | xargs -I PANE tmux send-keys -t PANE C-c
#sleep 0.2
#tmux list-panes -s -F "#{window_index}.#{pane_index}" | xargs -I PANE tmux send-keys -t PANE " source ~/.zshrc && fg > /dev/null 2>&1" C-m

# tmux-bell crashes process...
tmux set -g bell-action none

sessions=$(tmux ls 2> /dev/null | grep '^[0-9]\+:' | cut -f1 -d':')
for sess in $sessions
do
    for i in {1..10}; do tmux send-keys -t $sess: 'C-['; done
    tmux send-keys -t $sess: C-z
    tmux send-keys -t $sess: C-c
    sleep 0.2
    tmux send-keys -t $sess: " source ~/.zshrc && fg > /dev/null 2>&1" C-m
done
scratch=$(tmux ls 2> /dev/null | grep "scratchpad" | wc -l)
if [[ "$scratch" != "0" ]]; then
    for i in {1..10}; do tmux send-keys -t scratchpad: 'C-['; done
    tmux send-keys -t scratchpad: C-z
    tmux send-keys -t scratchpad: C-c
    sleep 0.2
    tmux send-keys -t scratchpad: " source ~/.zshrc && fg > /dev/null 2>&1" C-m
fi

#just for the tmux-bell...
tmux set -g bell-action any

neovim-reload.py


##### change gtk-theme
name=$(mondo get shell)
sed -i "s/gtk-theme-name=\".[^]]*\"/gtk-theme-name=\"$name\"/g" /home/philipp/.gtkrc-2.0
sed -i "s/gtk-icon-theme-name=\".[^]]*\"/gtk-icon-theme-name=\"$name\"/g" /home/philipp/.gtkrc-2.0
sed -i "s/gtk-theme-name=.*/gtk-theme-name=$name/g" /home/philipp/.config/gtk-3.0/settings.ini
sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=$name/g" /home/philipp/.config/gtk-3.0/settings.ini


##### change background-color
#convert /home/philipp/.xfiles/background/png-walls/dots.png -fill "$(xrdb -query|awk '/\*color20:/ {print $2}')" -opaque "#000000" /home/philipp/.xfiles/background/png-walls/dots8.png
#convert /home/philipp/.xfiles/background/png-walls/dots8.png -fill "$(xrdb -query|awk '/\*color18:/ {print $2}')" -opaque "#ffffff" /home/philipp/.xfiles/background/png-walls/dots16.png

#convert /home/philipp/.xfiles/background/png-walls/dots.png -fill "$(xrdb -query|awk '/\*color20:/ {print $2}')" -opaque "#000000" /home/philipp/.xfiles/background/png-walls/dots8.png
#convert /home/philipp/.xfiles/background/png-walls/dots8.png -fill "$(xrdb -query|awk '/\*color0:/ {print $2}')" -opaque "#ffffff" /home/philipp/.xfiles/background/png-walls/dots16.png

convert /home/philipp/.xfiles/background/bitmap-walls/patterns/dots_wide.xbm -fill "$(xrdb -query|awk '/\*color20:/ {print $2}')" -opaque "#000000" -fill "$(xrdb -query|awk '/\*color18:/ {print $2}')" +opaque "#ffffff" /home/philipp/.xfiles/background/png-walls/dots8.png
convert /home/philipp/.xfiles/background/png-walls/dots8.png -fill "$(xrdb -query|awk '/\*color20:/ {print $2}')" -opaque "#ffffff" /home/philipp/.xfiles/background/png-walls/dots16.png

hsetroot -tile /home/philipp/.xfiles/background/png-walls/dots16.png
#xsetroot -bitmap /home/philipp/.xfiles/background/bitmap-walls/patterns/dots_wide.xbm -fg "$(xrdb -query|awk '/\*color18:/ {print $2}')" -bg "$(xrdb -query|awk '/\*color20:/ {print $2}')"

#xsetroot -solid "$(xrdb -query|awk '/\*color0:/ {print $2}')"
#xsetroot -bitmap /home/philipp/.xfiles/background/bitmap-walls/patterns/line_diag8_1.xbm -bg "$(xrdb -query|awk '/\*color18:/ {print $2}')" -fg "$(xrdb -query|awk '/\*color8:/ {print $2}')"
#xsetroot -bitmap /home/philipp/.xfiles/background/bitmap-walls/patterns/dots_big.xbm -bg "$(xrdb -query|awk '/\*color18:/ {print $2}')" -fg "$(xrdb -query|awk '/\*color8:/ {print $2}')"
#xsetroot -bitmap /home/philipp/.xfiles/background/bitmap-walls/patterns/grey_32_28.xbm -fg "$(xrdb -query|awk '/\*color18:/ {print $2}')" -bg "$(xrdb -query|awk '/\*color7:/ {print $2}')"
#xsetroot -bitmap /home/philipp/.xfiles/background/bitmap-walls/patterns/check.xbm -fg "$(xrdb -query|awk '/\*color18:/ {print $2}')" -bg "$(xrdb -query|awk '/\*color8:/ {print $2}')"
#xsetroot -bitmap /home/philipp/.xfiles/background/bitmap-walls/patterns/chev_same.xbm -fg "$(xrdb -query|awk '/\*color18:/ {print $2}')" -bg "$(xrdb -query|awk '/\*color8:/ {print $2}')"


###### dwm-xrdb hack.... not refreshing in mondo... + rescale windows to fix glitches
xsetroot -name "fsignal:1"
xsetroot -name "fsignal:2"


##### restart nm-applet icon
killall nm-applet; nm-applet &
killall polkit-gnome-authentication-agent-1; /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
killall qutebrowser && qutebrowser &

