#!/bin/sh
#       _       _ _
# __  _(_)_ __ (_) |_ _ __ ___
# \ \/ / | '_ \| | __| '__/ __|
#  >  <| | | | | | |_| | | (__
# /_/\_\_|_| |_|_|\__|_|  \___|

##### fix for QT (and dconf-editor)...

#export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_FONT_DPI=64
export QT_QPA_PLATFORMTHEME=gtk2
  ## or
#export QT_QPA_PLATFORMTHEME=qt5ct

#export DESKTOP_SESSION=gnome		#or set to xfce for classic ui
#export XDG_CURRENT_DESKTOP=GNOME	#or set to XFCE for classic ui

##### pcmanfm needs this..
export XDG_MENU_PREFIX="lxde-"
export XDG_CURRENT_DESKTOP=LXDE

##### HDPI
#export GDK_SCALE=2
#export GDK_DPI_SCALE=0.8

##### merge in defaults and keymaps
xrdb -merge $HOME/.config/X11/Xresources
xmodmap $HOME/.config/X11/Xmodmap

##### start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

##### trackpoint settings
xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Speed" -0.4

##### keyboard speed
xset r rate 200 60

##### i did this (x230 setting and window manager)
xrandr --dpi 125.37 &

##### start clipmenu-service (do not enable, because then xsel cant read DISPLAY on start...)
systemctl --user start clipmenud

exec $HOME/.local/bin/dwm-starter
