#!/bin/sh

color00="19/17/1c"  # Base 00  - Black
color01="9E/26/58" # Base 08a - Red
color02="0A/72/72" # Base 0Ba - Green
color03="80/4E/1B" # Base 0Aa - Yellow
color04="37/4D/BB" # Base 0Da - Blue
color05="75/3A/C7" # Base 0Ea - Magenta
color06="19/6B/A6" # Base 0Ca - Cyan
color07="8b/87/92"  # Base 05  - White
color08="65/5f/6d"  # Base 03  - Bright Black
color09="be/46/78"  # Base 08  - Bright Red
color10="2a/92/92"  # Base 0B  - Bright Green
color11="a0/6e/3b"  # Base 0A  - Bright Yellow
color12="57/6d/db"  # Base 0D  - Bright Blue
color13="95/5a/e7"  # Base 0E  - Bright Magenta
color14="39/8b/c6"  # Base 0C  - Bright Cyan
color15="ef/ec/f4"  # Base 07  - Bright White
color16="aa/57/3c"  # Base 09
color17="bf/40/bf"  # Base 0F
color18="26/23/2a"  # Base 01
color19="58/52/60"  # Base 02
color20="7e/78/87"  # Base 04
color21="e2/df/e7"  # Base 06
color_foreground="8b/87/92" # Base 05
color_background="19/17/1c" # Base 00

if [ -n "$TMUX" ]; then
  # Tell tmux to pass the escape sequences through
  # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
  put_template() { printf '\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\' $@; }
  put_template_var() { printf '\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\' $@; }
  put_template_custom() { printf '\033Ptmux;\033\033]%s%s\033\033\\\033\\' $@; }
elif [ "${TERM%%[-.]*}" = "screen" ]; then
  # GNU screen (screen, screen-256color, screen-256color-bce)
  put_template() { printf '\033P\033]4;%d;rgb:%s\007\033\\' $@; }
  put_template_var() { printf '\033P\033]%d;rgb:%s\007\033\\' $@; }
  put_template_custom() { printf '\033P\033]%s%s\007\033\\' $@; }
elif [ "${TERM%%-*}" = "linux" ]; then
  put_template() { [ $1 -lt 16 ] && printf "\e]P%x%s" $1 $(echo $2 | sed 's/\///g'); }
  put_template_var() { true; }
  put_template_custom() { true; }
else
  put_template() { printf '\033]4;%d;rgb:%s\033\\' $@; }
  put_template_var() { printf '\033]%d;rgb:%s\033\\' $@; }
  put_template_custom() { printf '\033]%s%s\033\\' $@; }
fi

# 16 color space
put_template 0  $color00
put_template 1  $color01
put_template 2  $color02
put_template 3  $color03
put_template 4  $color04
put_template 5  $color05
put_template 6  $color06
put_template 7  $color07
put_template 8  $color08
put_template 9  $color09
put_template 10 $color10
put_template 11 $color11
put_template 12 $color12
put_template 13 $color13
put_template 14 $color14
put_template 15 $color15

# 256 color space
put_template 16 $color16
put_template 17 $color17
put_template 18 $color18
put_template 19 $color19
put_template 20 $color20
put_template 21 $color21

# foreground / background / cursor color
put_template_var 10 $color_foreground
if [ "$BASE16_SHELL_SET_BACKGROUND" != false ]; then
  put_template_var 11 $color_background
  if [ "${TERM%%-*}" = "rxvt" ]; then
    put_template_var 708 $color_background # internal border (rxvt)
  fi
fi
put_template_custom 12 ";7" # cursor (reverse video)

# clean up
unset -f put_template
unset -f put_template_var
unset -f put_template_custom
unset color00
unset color01
unset color02
unset color03
unset color04
unset color05
unset color06
unset color07
unset color08
unset color09
unset color10
unset color11
unset color12
unset color13
unset color14
unset color15
unset color16
unset color17
unset color18
unset color19
unset color20
unset color21
unset color_foreground
unset color_background
