#!/bin/bash
# This script is executed every time a theme is applied.
# Each generator can have it's own _mondo-apply script.

# The default syntax is bash, but by changing the shebang,
# one could use another language (f.i. perl or python).

# $1 is equal to: $MONOD_DIR/generator/TYPE/THEME[.extensions]

# If this script is not needed, this file can safely be removed.
# (removing the file, will improve execution speed)

# MONDO_DIR="${1%%/generator*}"
# THIS_DIR="${1%/*}"
# THIS_GENERATOR="${THIS_DIR##*/}"
# THIS_FILE="${1##*/}"
# THIS_THEME="${THIS_FILE%.*}"

# To source the settings file one could use this:
# source "${THIS_DIR}/_mondo-settings"

########################################################
##### dwm-cmdcustomize patched #########################
########################################################
#colorfile="/home/philipp/.xinitrc"
#resources="-nbg -nfg -nbo -nfl -sbg -sfg -sbo -sfl -ibg -ifg -ibo -abg -afg -abo -dnb -dnf -dsb -dsf"
#for r in $resources; do
#	xrvar=$(cat /home/philipp/.config/dwm/mondo-colors | awk -v reso=$r '$1~reso{print $2}')
#	sed -i --follow-symlinks "/$r/c\\$r \"#$xrvar\" \\\\" "$colorfile"
#done
#
# ##### falls bei der letzten zeile kein "\" am ende stehen soll !! (dann in der oberen liste loeschen) :
# #lastres=$(cat /home/philipp/.config/dwm/mondo-colors | awk '/-dsf/{print $2}')
# #sed -i --follow-symlinks "/-dsf /c\\-dsf \"#$lastres\"" "$colorfile"

########################################################
##### dwm-xrdb patched #################################
########################################################
#xsetroot -name "fsignal:1"
